### ISSUE TITLE
add support for other models

### ISSUE THREAD

**Issue by yaoguany** [THUDM/LongBench#10]
现有的代码是为glm tokenizer的，其他decoder-only model的tokenizer没有build_prompt()这个方法，需要自己在前面加上：
```
def build_prompt(query, history=None):
    if history is None:
        history = []
    prompt = ""
    for i, (old_query, response) in enumerate(history):
        prompt += "[Round {}]\n\n问：{}\n\n答：{}\n\n".format(i + 1, old_query, response)
    prompt += "[Round {}]\n\n问：{}\n\n答：".format(len(history) + 1, query)
    return prompt
```
以及其他模型load时在pred.py 43行需要使用AutoModelForCausalLM方法。

**Comment by bys0318** [comment]
是的，我们代码里的`build_prompt()`方法只是针对ChatGLM2模型的，我们正在整理所有模型的测试代码，并将在第一时间将整理好的代码更新到这个库中😊

**Comment by Fusionplay** [comment]
> 

其它模型需要使用这个build_prompt吗，不太清楚，使用与否的区别是什么

**Comment by bojone** [comment]
> 是的，我们代码里的`build_prompt()`方法只是针对ChatGLM2模型的，我们正在整理所有模型的测试代码，并将在第一时间将整理好的代码更新到这个库中😊

主要是你们给出了其他模型比如llama2-7b-chat的结果，就应当尽量把对应的`build_prompt`给出（或者如果跟chatglm2-6b一样的话直接补充说明一下），这样我们才能与之对比，因为很多模型都对prompt相当敏感的。

**Comment by bys0318** [comment]
我们现在给出了所有模型的评测代码，应该可以轻松复现我们汇报的结果了～
