### ISSUE TITLE
About prompt

### ISSUE THREAD

**Issue by ftgreat** [THUDM/LongBench#11]
As https://github.com/THUDM/LongBench/blob/main/pred.py#L21 says, chat models are better off without build prompt on these tasks. 

Could you please explain some details or references about it? thanks.

**Comment by bys0318** [comment]
Compared to the question-answering format of chat mode, these tasks (code completion, few-shot learning) more resembles the completion mode during pre-training, where answers are generated in a completion-style based on previous context. Therefore, we did not add a build prompt to these tasks. During experiments, we also found that adding a build prompt to these tasks would lead the model to generate more dialogue-style responses, which deviate from the original purpose of the tasks.
