### ISSUE TITLE
关于截断长度的公平性问题

### ISSUE THREAD

**Issue by bojone** [THUDM/LongBench#12]
在首页的表格中，Llama2-7B-chat-4k的英文平均效果是29.0，ChatGLM2-6B是26.0，也就是Llama2-7B-chat-4k超过了ChatGLM2-6B。

但Llama2-7B-chat-4k只是一个4k模型，看pred.py的话，ChatGLM2-6B去到了31.5k，换言之ChatGLM2-6B是真的long context来处理的，而根据首页的说法，Llama2-7B-chat-4k应该是将context通过从中间截断来控制长度在3.5k内？如果是的话，这两者的比较是否公平？或者更准确地说，这两者的比较是否有意义？

Llama2-7B-chat-4k效果更好，说明答案的关键信息多数还是集中在context的首尾，如果所有模型都从中间截断到3.5k内，那么说不准靠后的模型都能获得较大提升，但总感觉很奇怪。当然，从结果论来看，目前的做法没有什么不妥。我不是想质疑什么，只是提出这个疑问，目前我也没有什么好的解决办法。估计是目前的测试数据偏爱于从中间截断这一预处理手段，以至于无法评估出真正有价值的long contex技术。

**Comment by bys0318** [comment]
谢谢您的关注！首先，我们并不认为这是截断方案带来的不公平性，因为考虑到instruction经常在prompt的首尾，左/右截断可能会将任务指令截取而使得模型不知道该输出什么。相比之下，中间截断是一种更实用的截断方式，而且我们推测一些api模型内部也是采用的类似的截断方案。当然，也正如您所说，关键信息可能多数集中在context的首尾，我们也会比较不同截断方式下的模型效果来发掘数据中的这类bias。
针对您所说的不同模型在不同截断长度下比较，比如Llama2-7B-chat-4k在3.5k长度进行截断，达到了比ChatGLM2-6B在31.5k长度截断下更好的英文效果，我们认为这正说明了一些模型对于长文本的处理能力欠佳，尚未能在其能接受的最大长度上有较优的表现。当然，我们在即将发布的论文中也加入了不同模型在相同截断长度下的效果对比，来比较给入相同信息时，不同模型的文本理解能力。
最后，欢迎大家探讨如何最公平地评测不同模型的长文本理解能力！

**Comment by bys0318** [comment]
BTW，由于我们的数据集都是根据现实应用场景来采样并构建的，是比较贴合真实分布的，也就是说，这些数据肯定继承了真实分布中的一些特定bias，例如关键信息可能会更常在context的特定位置（如首尾）。至于这类bias是否会引入评测中的不公平，我们对benchmark构建的想法是——一种方式就是类似LongBench，从实际需求出发，即便数据中存在bias但是这种bias是真实存在的，而评测结果也会更贴近用户体验；另一种方案就是通过人工构造，通过对能力的细分来设计并构造相应任务，例如构建一些必须用全部context才能回答的任务来评价模型的长文本能力。
