### ISSUE TITLE
Questions on dataset answers.

### ISSUE THREAD

**Issue by chengeharrison** [THUDM/LongBench#15]
Hi there, I am a little confused about the answers in the dataset.

In dataset `nq`, I can see a sample whose answers contain same elements like `Carey Mulligan` and `Matthias Schoenaerts`. Actually, other samples also have duplicated answers. It is supposed to be like that?

Thanks for your reply!

![20230816-160211](https://github.com/THUDM/LongBench/assets/70520919/ec9a7041-2164-41f9-a918-bb989011e0d4)

**Comment by bys0318** [comment]
Thanks for pointing it out! We have noticed that there are some irregular patterns in the current `nq` dataset (luckily they do not affect the evaluation results), we will update this dataset soon!

**Comment by chengeharrison** [comment]
Thanks!

**Comment by bys0318** [comment]
Hi! We have updated the datasets in LongBench.
