### ISSUE TITLE
超长文本的推理OOM

### ISSUE THREAD

**Issue by freshbirdDD** [THUDM/LongBench#17]
您好，我目前在做一些模型的超长文本评测，在使用LongBench，当length设置为20k的时候，单张80G的A100做7B模型的推理就会OOM，想知道您这边之前做评测的时候是怎么解决这个问题的

**Comment by bys0318** [comment]
请问您用哪个模型会超显存呢？

**Comment by davidlvxin** [comment]
如果模型没有使用Flash Attention，那么可能会OOM，建议您参考[ChatGLM2-6B-32K](https://huggingface.co/THUDM/chatglm2-6b-32k/blob/main/modeling_chatglm.py)将其转换为Flash Attention的实现，必要时更改KV Cache的存储方式。如果优化得当，在32K的长度下，6B模型只需要约20G的显存。

**Comment by freshbirdDD** [comment]
@bys0318 我使用了baichuan7b和llama 7b，直接用HF格式的模型加载

**Comment by freshbirdDD** [comment]
@davidlvxin 您是说这些直接按HF格式的模型推理出现OOM是正常情况是么，后续您这边有考虑在LongBench的仓库中加入将HF格式的模型一键转化成Flash Attention实现的功能么...

**Comment by Aran-Guo** [comment]
> 如果模型没有使用Flash Attention，那么可能会OOM，建议您参考[ChatGLM2-6B-32K](https://huggingface.co/THUDM/chatglm2-6b-32k/blob/main/modeling_chatglm.py)将其转换为Flash Attention的实现，必要时更改KV Cache的存储方式。如果优化得当，在32K的长度下，6B模型只需要约20G的显存。

请问我使用chatglm2-6b-32k最多也是能训练1w上下文，这是什么原因？

**Comment by davidlvxin** [comment]
训练需要存储很多额外的参数，如梯度，fp32的模型参数拷贝，优化器状态等，所以会比inference耗费更多的显存。我们在8卡80G A100上进行过测试，开启DeepSpeed Zero3和gradient_checkpointing的情况下，可以做到32k长度的训练，可以调整到这个配置再次尝试一下

**Comment by bys0318** [comment]
@freshbirdDD 我们已经在更新中加入了对Flash Attention的支持

**Comment by Aran-Guo** [comment]
> 训练需要存储很多额外的参数，如梯度，fp32的模型参数拷贝，优化器状态等，所以会比inference耗费更多的显存。我们在8卡80G A100上进行过测试，开启DeepSpeed Zero3和gradient_checkpointing的情况下，可以做到32k长度的训练，可以调整到这个配置再次尝试一下

不好意思，打错字了，我用给的代码直接跑ChatGLM推理，也是爆显存，最多只能跑10k上下文。

**Comment by McJackTang** [comment]
> > 训练需要存储很多额外的参数，如梯度，fp32的模型参数拷贝，优化器状态等，所以会比inference耗费更多的显存。我们在8卡80G A100上进行过测试，开启DeepSpeed Zero3和gradient_checkpointing的情况下，可以做到32k长度的训练，可以调整到这个配置再次尝试一下
> 
> 不好意思，打错字了，我用给的代码直接跑ChatGLM推理，也是爆显存，最多只能跑10k上下文。

您好，使用ChatGLM进行推理并不需要很大显存，我测试在单卡A100上是可以正常运行的；ChatGLM-6B-32k的上下文最大支持可以达到32k的token数量，对英文词数和中文字数可能会有差异

**Comment by McJackTang** [comment]
@Aran-Guo 推理使用Flash Attention可以大幅降低显存，在ChatGLM2的实现中，Pytorch版本大于2.0会自动开启该功能。如您遇到OOM问题，可以贴上您所使用的环境和代码。
