### ISSUE TITLE
About the calculation of the Avg score?

### ISSUE THREAD

**Issue by WSPeng** [THUDM/LongBench#19]
it appears that the average is calculated as the direct mean of each category (https://github.com/THUDM/LongBench#english). A more fair approach may be to calculate a weighted mean using the number of each category?

**Comment by bys0318** [comment]
In our evaluation, we treat each categories as equally important hence we take the average over each task category (single-doc QA, multi-doc QA, etc). We also believe that the number of tasks in each task category is in no way an indicator of their importance.

**Comment by coranholmes** [comment]
> In our evaluation, we treat each categories as equally important hence we take the average over each task category (single-doc QA, multi-doc QA, etc). We also believe that the number of tasks in each task category is in no way an indicator of their importance.

I have a related question. As some tasks use rouge while others use F1, do you average all tasks regardless of the evaluation metrics?

**Comment by bys0318** [comment]
Yes, we average the task scores regardless of the evaluation metrics. We are aware of the potential fairness issue, since different metrics are not well aligned. Let's keep in mind that the score on each task / task category is equally important for diagnosing the capability of an LLM.
