### ISSUE TITLE
Error with multi-gpus

### ISSUE THREAD

**Issue by Xnhyacinth** [THUDM/LongBench#23]
在测试llama2时，device_map=''auto'' 即多gpu会导致flash-attn部分报错，但在另一台机器上测试的时候没有问题，其他模型也没有问题，报错如下：
`RuntimeError: CUDA error: invalid configuration argument
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with TORCH_USE_CUDA_DSA to enable device-side assertions.`

*** Error in `python': free(): invalid pointer: 0x0000557f6c3bedf0 ***
======= Backtrace: =========
/lib64/libc.so.6(+0x79a1c)[0x7f72132eaa1c]
/lib64/libc.so.6(+0x7f498)[0x7f72132f0498]
/lib64/libc.so.6(+0x8007c)[0x7f72132f107c]
/usr/local/anaconda3/envs/py39/lib/python3.9/site-packages/numpy/core/_multiarray_umath.cpython-39-x86_64-linux-gnu.so(+0x390e17)[0x7f720bcb3e17]
python(+0x136d16)[0x557f6aa9cd16]
python(+0x2767c8)[0x557f6abdc7c8]
python(Py_FinalizeEx+0x1a4)[0x557f6abdc984]
python(Py_RunMain+0x111)[0x557f6abe3331]
python(Py_BytesMain+0x39)[0x557f6abe3729]
/lib64/libc.so.6(__libc_start_main+0xee)[0x7f7213295bde]
python(+0x203667)[0x557f6ab69667]
======= Memory map: ========
200000000-200200000 ---p 00000000 00:00 0 
200200000-200400000 rw-s 00000000 00:05 92236                            /dev/nvidiactl
200400000-200600000 rw-s 00000000 00:05 33913                            /dev/nvidia5
200600000-203600000 rw-s 00000000 00:05 92236                            /dev/nvidiactl
203600000-204600000 ---p 00000000 00:00 0 
204600000-204800000 rw-s 00000000 00:05 92236                            /dev/nvidiactl
204800000-204a00000 rw-s 00000000 00:05 92236                            /dev/nvidiactl
204a00000-204c00000 rw-s 204a00000 00:05 81474                           /dev/nvidia-uvm
204c00000-204e00000 rw-s 00000000 00:05 92236                            /dev/nvidiactl
204e00000-205000000 ---p 00000000 00:00 0 
205000000-205200000 rw-s 00000000 00:05 92236                            /dev/nvidiactl
205200000-205600000 ---p 00000000 00:00 0 
205600000-205800000 rw-s 00000000 00:05 92236                            /dev/nvidiactl
205800000-205a00000 rw-s 00000000 00:05 92254                            /dev/nvidia6
205a00000-208a00000 rw-s 00000000 00:05 92236                            /dev/nvidiactl
208a00000-209a00000 ---p 00000000 00:00 0 
209a00000-209c00000 rw-s 00000000 00:05 92236                            /dev/nvidiactl
209c00000-209e00000 rw-s 00000000 00:05 92236                            /dev/nvidiactl
209e00000-20a000000 rw-s 209e00000 00:05 81474                           /dev/nvidia-uvm
20a000000-20a200000 rw-s 00000000 00:05 92236                            /dev/nvidiactl
20a200000-20a400000 ---p 00000000 00:00 0 
20a400000-20a600000 rw-s 00000000 00:05 92236                            /dev/nvidiactl
20a600000-20aa00000 ---p 00000000 00:00 0 
20aa00000-20ac00000 rw-s 00000000 00:05 92236                            /dev/nvidiactl
20ac00000-20ae00000 rw-s 00000000 00:05 78022                            /dev/nvidia7
20ae00000-20de00000 rw-s 00000000 00:05 92236                            /dev/nvidiactl
20de00000-20ee00000 ---p 00000000 00:00 0 
20ee00000-20f000000 rw-s 00000000 00:05 92236                            /dev/nvidiactl
20f000000-20f200000 rw-s 00000000 00:05 92236                            /dev/nvidiactl
20f200000-20f400000 rw-s 20f200000 00:05 81474                           /dev/nvidia-uvm
20f400000-20f600000 rw-s 00000000 00:05 92236                            /dev/nvidiactl
20f600000-20f800000 ---p 00000000 00:00 0 
20f800000-20fa00000 rw-s 00000000 00:05 92236                            /dev/nvidiactl
20fa00000-500200000 ---p 00000000 00:00 0 
10000000000-1000c000000 ---p 00000000 00:00 0 
557f6a966000-557f6a9c2000 r--p 00000000 08:01 1612918380                 /usr/local/anaconda3/envs/py39/bin/python3.9
557f6a9c2000-557f6abe6000 r-xp 0005c000 08:01 1612918380                 /usr/local/anaconda3/envs/py39/bin/python3.9
557f6abe6000-557f6acd2000 r--p 00280000 08:01 1612918380                 /usr/local/anaconda3/envs/py39/bin/python3.9
557f6acd2000-557f6acd8000 r--p 0036b000 08:01 1612918380                 /usr/local/anaconda3/envs/py39/bin/python3.9
557f6acd8000-557f6ad0f000 rw-p 00371000 08:01 1612918380                 /usr/local/anaconda3/envs/py39/bin/python3.9
557f6ad0f000-557f6ad31000 rw-p 00000000 00:00 0 
557f6c1ef000-5580341cb000 rw-p 00000000 00:00 0                          [heap]
7f69e0000000-7f69f6000000 ---p 00000000 00:00 0 
7f69f8000000-7f6a12000000 ---p 00000000 00:00 0 
7f6a14000000-7f6a2e000000 ---p 00000000 00:00 0 
7f6a30000000-7f6a42000000 ---p 00000000 00:00 0 
7f6ad2000000-7f6ae8000000 ---p 00000000 00:00 0 
7f6aea000000-7f6af6000000 ---p 00000000 00:00 0 
7f6b5a000000-7f6b77800000 ---p 00000000 00:00 0 
7f6b77800000-7f6b77bf1000 rw-s 00000000 00:04 4122933                    /dev/zero (deleted)
7f6b77bf1000-7f6bc4000000 ---p 00000000 00:00 0 
7f6bc4000000-7f6bc4021000 rw-p 00000000 00:00 0 
7f6bc4021000-7f6bc8000000 ---p 00000000 00:00 0 
7f6bca000000-7f6bd8000000 ---p 00000000 00:00 0 
7f6bda000000-7f6be7a00000 ---p 00000000 00:00 0 
7f6be7a00000-7f6be7df1000 rw-s 00000000 00:04 4138955                    /dev/zero (deleted)
7f6be7df1000-7f6bf4000000 ---p 00000000 00:00 0 
7f6bf6000000-7f6c10000000 ---p 00000000 00:00 0 
7f6c12000000-7f6c2c000000 ---p 00000000 00:00 0 
7f6c2e000000-7f6c48000000 ---p 00000000 00:00 0 
7f6c4a000000-7f6c64000000 ---p 00000000 00:00 0 
7f6c66000000-7f6c88000000 ---p 00000000 00:00 0 
7f6c8a000000-7f6c92000000 ---p 00000000 00:00 0 
7f6c94000000-7f6ca0000000 ---p 00000000 00:00 0 
7f6ca2000000-7f6cbc000000 ---p 00000000 00:00 0 
7f6cbe000000-7f6cd8000000 ---p 00000000 00:00 0 
7f6cda000000-7f6cf4000000 ---p 00000000 00:00 0 
7f6cf6000000-7f6d10000000 ---p 00000000 00:00 0 
7f6d12000000-7f6d2c000000 ---p 00000000 00:00 0 
7f6d2e000000-7f6d48000000 ---p 00000000 00:00 0 
7f6d4a000000-7f6d64000000 ---p 00000000 00:00 0 
7f6d66000000-7f6d80000000 ---p 00000000 00:00 0 
7f6d82000000-7f6d9c000000 ---p 00000000 00:00 0 
7f6d9e000000-7f6db8000000 ---p 00000000 00:00 0 
7f6dba000000-7f6dd4000000 ---p 00000000 00:00 0 
7f6dd6000000-7f6df0000000 ---p 00000000 00:00 0 
7f6df2000000-7f6e0c000000 ---p 00000000 00:00 0 
7f6e0e000000-7f6e28000000 ---p 00000000 00:00 0 
7f6e2a000000-7f6e44000000 ---p 00000000 00:00 0 
7f6e46000000-7f6e60000000 ---p 00000000 00:00 0 
7f6e62000000-7f6e7c000000 ---p 00000000 00:00 0 
7f6e7e000000-7f6e98000000 ---p 00000000 00:00 0 
7f6e9a000000-7f6eb4000000 ---p 00000000 00:00 0 
7f6eb6000000-7f6ed8000000 ---p 00000000 00:00 0 
7f6eda000000-7f6ee2000000 ---p 00000000 00:00 0 
7f6ee4000000-7f6f09000000 ---p 00000000 00:00 0 
7f6f09000000-7f6f09200000 rw-s 00000000 00:04 3855178                    /dev/zero (deleted)
7f6f09200000-7f6f1c000000 ---p 00000000 00:00 0 
7f6f1c000000-7f6f1c021000 rw-p 00000000 00:00 0 
7f6f1c021000-7f6f20000000 ---p 00000000 00:00 0 
7f6f22000000-7f6f22800000 ---p 00000000 00:00 0 
7f6f22800000-7f6f22a00000 rw-s 00000000 00:05 92236                      /dev/nvidiactl
7f6f22a00000-7f6f22c00000 rw-s 00000000 00:04 3855174                    /dev/zero (deleted)
7f6f22c00000-7f6f22e00000 rw-s 00000000 00:04 3855175                    /dev/zero (deleted)
7f6f22e00000-7f6f23400000 ---p 00000000 00:00 0 
7f6f23400000-7f6f23600000 rw-s 00000000 00:05 92236                      /dev/nvidiactl
7f6f23600000-7f6f23800000 rw-s 00000000 00:04 3855177                    /dev/zero (deleted)
7f6f23800000-7f6f23b33000 rw-s 00000000 00:05 92236                      /dev/nvidiactl
7f6f23b33000-7f6f43000000 ---p 00000000 00:00 0 
7f6f43000000-7f6f43200000 rw-s 00000000 00:04 3855173                    /dev/zero (deleted)
7f6f43200000-7f6f56200000 ---p 00000000 00:00 0 
7f6f56200000-7f6f56400000 rw-s 00000000 00:05 92236                      /dev/nvidiactl
7f6f56400000-7f6f56600000 rw-s 00000000 00:04 3855172                    /dev/zero (deleted)
7f6f56600000-7f6f56933000 rw-s 00000000 00:05 92236                      /dev/nvidiactl
7f6f56933000-7f6f58000000 ---p 00000000 00:00 0 
7f6f58000000-7f6f58021000 rw-p 00000000 00:00 0 
7f6f58021000-7f6f5c000000 ---p 00000000 00:00 0 
7f6f5e000000-7f6f5f600000 ---p 00000000 00:00 0 
7f6f5f600000-7f6f5f800000 rw-s 00000000 00:05 92236                      /dev/nvidiactl
7f6f5f800000-7f6f5fa00000 rw-s 00000000 00:04 3855169                    /dev/zero (deleted)
7f6f5fa00000-7f6f5fc00000 rw-s 00000000 00:04 3855170                    /dev/zero (deleted)
7f6f5fc00000-7f6f66000000 ---p 00000000 00:00 0 
7f6f67562000-7f6f6aab1000 rw-p 00000000 00:00 0 
7f6f6e000000-7f6f78000000 ---p 00000000 00:00 0 
7f6f78cb5000-7f6f7a000000 rw-p 00000000 00:00 0 
7f6f7a000000-7f6f89000000 ---p 00000000 00:00 0 
7f6f89000000-7f6f89200000 rw-s 00000000 00:04 3855168                    /dev/zero (deleted)
7f6f89200000-7f6f9c000000 ---p 00000000 00:00 0 
7f6f9c000000-7f6f9c021000 rw-p 00000000 00:00 0 
7f6f9c021000-7f6fa0000000 ---p 00000000 00:00 0 
7f6fa0df8000-7f6fa2000000 rw-p 00000000 00:00 0 
7f6fa2000000-7f6fa2400000 ---p 00000000 00:00 0 
7f6fa2400000-7f6fa2600000 rw-s 00000000 00:05 92236                      /dev/nvidiactl
7f6fa2600000-7f6fa2800000 rw-s 00000000 00:04 3855163                    /dev/zero (deleted)
7f6fa2800000-7f6fa2a00000 rw-s 00000000 00:04 3855164                    /dev/zero (deleted)
7f6fa2a00000-7f6fa3000000 ---p 00000000 00:00 0 
7f6fa3000000-7f6fa3200000 rw-s 00000000 00:05 92236                      /dev/nvidiactl
7f6fa3200000-7f6fa3400000 rw-s 00000000 00:04 3855166                    /dev/zero (deleted)
7f6fa3400000-7f6fa3733000 rw-s 00000000 00:05 92236                      /dev/nvidiactl
7f6fa3733000-7f6fa4000000 ---p 00000000 00:00 0 
7f6fa4000000-7f6fa4029000 rw-p 00000000 00:00 0 
7f6fa4029000-7f6fa8000000 ---p 00000000 00:00 0 
7f6fa8000000-7f6fa8029000 rw-p 00000000 00:00 0 
7f6fa8029000-7f6fac000000 ---p 00000000 00:00 0 
7f6fac000000-7f6fac029000 rw-p 00000000 00:00 0 
7f6fac029000-7f6fb0000000 ---p 00000000 00:00 0 
7f6fb0000000-7f6fb0029000 rw-p 00000000 00:00 0 
7f6fb0029000-7f6fb4000000 ---p 00000000 00:00 0 
7f6fb4000000-7f6fb4029000 rw-p 00000000 00:00 0 
7f6fb4029000-7f6fb8000000 ---p 00000000 00:00 0 
7f6fb8000000-7f6fb8029000 rw-p 00000000 00:00 0 
7f6fb8029000-7f6fbc000000 ---p 00000000 00:00 0 
7f6fbc000000-7f6fbc029000 rw-p 00000000 00:00 0 
7f6fbc029000-7f6fc0000000 ---p 00000000 00:00 0 
7f6fc0000000-7f6fc0029000 rw-p 00000000 00:00 0 
7f6fc0029000-7f6fc4000000 ---p 00000000 00:00 0 
7f6fc4000000-7f6fc4029000 rw-p 00000000 00:00 0 
7f6fc4029000-7f6fc8000000 ---p 00000000 00:00

**Comment by ponytaill** [comment]
请问你知道原因了吗，我也遇到了这个问题 @Xnhyacinth

**Comment by Xnhyacinth** [comment]
> 请问你知道原因了吗，我也遇到了这个问题 @Xnhyacinth

是机器的问题（a6000），具体原因没查
