### ISSUE TITLE
llama2 chat's template

### ISSUE THREAD

**Issue by Arist12** [THUDM/LongBench#26]
https://github.com/THUDM/LongBench/blob/main/pred.py#L29C10-L29C10

According to this link https://gpus.llm-utils.org/llama-2-prompt-template/, llama2 chat's prompt format is different from your code.
```<s>[INST] {user_message_1} [/INST]```

**Comment by bys0318** [comment]
Keen observation! We indeed omit the system prompts `<<SYS>> <</SYS>>` in Llama2 because in real scenarios, users typically do not add system prompts to their inputs explicitly. Moreover, system prompts are not identified for other models. Hence, for fair comparison, we decide not to use system prompts for Llama2. A similar question is also raised in #2.

**Comment by Arist12** [comment]
Thanks for your reply!
But I'm not talking about the system message. In the repository, the chat template for llama2-chat is:
```
f"[INST]{prompt}[/INST]"
```

But according to the above blog, it's like below: 
```
<s>[INST] {user_message_1} [/INST]
```

The space between [INST] and the message, and the prefix <s> is missing. I'm not sure if it would be better to use the second format according to the blog.

**Comment by bys0318** [comment]
The begin of sequence token `<s>` is automatically added by Llama2 tokenizer. We anticipate that space will not significantly affect performance. Nevertheless, we invite you to test Llama2 on LongBench using the prompt from the original blog post, and report back to us if there is a noticeable gap in performance compared to our test results. Thanks in advance!

**Comment by Arist12** [comment]
Thanks so much for your kind reply, I'll test whether the space matters and report back :)

**Comment by bys0318** [comment]
Cool! Thanks for pointing out this potential problem anyway~
