### ISSUE TITLE
No repeat_kv in llama_flash_attn_monkey_patch.py ?

### ISSUE THREAD

**Issue by Orion-Zheng** [THUDM/LongBench#27]
In llama 2's code, the code use repeat_kv before attention to repeat k/v heads(GQA).
<img width="865" alt="image" src="https://github.com/THUDM/LongBench/assets/62330719/8dee36ef-8135-4abb-9215-51cd4dae1792">
But I didn't find any repeat_kv in the llama_flash_attn_monkey_patch.py.
I think this should be a mistake🤔If llama 2 is evaluated without repeat_kv, I think the result would also be incorrect.
Is my understanding correct?

**Comment by bys0318** [comment]
Thanks for your attention! We don't think this would influence the result. Feel free to compare the generation results of Llama 2 w/ and w/o the llama_flash_attn_monkey_patch.py and check for yourself~

**Comment by Orion-Zheng** [comment]
Thank you. 😃After checking the original configuration of LLaMA-2, I found
self.num_key_value_groups = self.num_heads // self.num_key_value_heads
<img width="311" alt="image" src="https://github.com/THUDM/LongBench/assets/62330719/e684c3e1-6c8a-428b-9771-a994809c9f18">
it mean by default self.num_key_value_groups=1, so it doesn't matter whether adding it or not.
But just to be safe, I think it will be more flexible if we add this, because maybe some people will adjust the num_key_value_heads when using GQA

**Comment by bys0318** [comment]
Thanks for pointing it out! The current llama_flash_attn_monkey_patch does not support GQA, feel free to submit a merge request to add this feature.
