### ISSUE TITLE
Is it necessary to add build_prompt to the tokenizer of chatglm3-6b-32k in pred.py?

### ISSUE THREAD

**Issue by MrYxJ** [THUDM/LongBench#30]
Congratulations, this data set did a great job. I ran into no build_prompt in tokenizer when using pred.py to predict chatglm3-6b-32k. At the same time, I noticed that tokenization_chatglm.py in [chatglm2-6b-32k](https://huggingface.co/THUDM/chatglm2-6b-32k/blob/main/tokenization_chatglm.py) does have a build_prompt() method, but not in chatglm3-6b-32k. Does chatglm3-6b-32k not need this prompt?

**Comment by bys0318** [comment]
Thanks for pointing it out! We have update `build_prompt()` in `pred.py` to support chatglm3.

**Comment by bys0318** [comment]
Oops, fixed now.
