### ISSUE TITLE
KeyError: 'retrieved'

### ISSUE THREAD

**Issue by liujingcs** [THUDM/LongBench#32]
Thanks for great work! I've encountered an issue while running the `pred.py` script for long context compression evaluation based on retrieval. The script is throwing a KeyError: 'retrieved,' which is preventing me from making progress. Upon investigation, it appears that the 'LongBench.py' script may not have the necessary code to handle data with the 'retrieved' key.

**Comment by bys0318** [comment]
Thanks for your attention! Make sure you have followed the steps in [retrieval](https://github.com/THUDM/LongBench/tree/main/retrieval), since the 'retrieved' key is only added after you run the retrieval.

**Comment by liujingcs** [comment]
Thank you for your prompt response. Upon conducting a more thorough examination, it seems that there is a missing data extraction process for 'retrieved' within the [LongBench.py](https://huggingface.co/datasets/THUDM/LongBench/blob/main/LongBench.py) file. This issue appears to be particularly related to the _generate_examples function.

**Comment by bys0318** [comment]
We have added a customized [LongBench.py](https://github.com/THUDM/LongBench/blob/main/retrieval/LongBench.py) under folder `retrieval`. Please check if this resolves your issue.
