### ISSUE TITLE
classification_score计算得分代码有误

### ISSUE THREAD

**Issue by zhangleiedu** [THUDM/LongBench#36]
https://github.com/THUDM/LongBench/blob/main/metrics.py#L98
代码中，em_match_list != 0 会永远为True，此处是否修改为 len(em_match_list )!=0

**Comment by bys0318** [comment]
谢谢你的发现！我们在评测时采用的就是hard match（如果输出的分类和正确的类别是完全match上的则判断为正确，否则为错误），后面的无用代码已经删除。再次感谢你的发现。
