### ISSUE TITLE
Missing passage_retrieval_en and and passage_retrieval_zh in dataset2prompt.json and dataset2maxlen.json

### ISSUE THREAD

**Issue by chaochen99** [THUDM/LongBench#4]
see title. 

Thanks!

**Comment by bys0318** [comment]
Thanks for pointing it out! We've updated the according config files.

**Comment by chaochen99** [comment]
the same as eval.py. please check it.

**Comment by bys0318** [comment]
Sure, all fixed now~

**Comment by chaochen99** [comment]
Thanks for your reply.
And I have encountered a new problem when I run eval.py to evaluate passage_retrieval_zh, the program error is
`  File "LongBench/metrics.py", line 71, in retrieval_zh_score
    ground_truth_id = matches[0]
IndexError: list index out of range`
Could you see if it works?

**Comment by bys0318** [comment]
We've updated our data on [HF Repo](https://huggingface.co/datasets/THUDM/LongBench), please download the newest version. We're deeply sorry for the inconvenience.

**Comment by bys0318** [comment]
BTW, the only updated file is `passage_retrieval_zh`, so you don't have to rerun the evaluation on other datasets.
