### ISSUE TITLE
如何评测GPT-3.5或GPT-4

### ISSUE THREAD

**Issue by jing-my** [THUDM/LongBench#47]
好像只提供了开源模型的预测和评测，所以请想问下如何复现GPT的评测结果呢？

**Comment by bys0318** [comment]
您好，复现GPT的结果只需在[pred.py](https://github.com/THUDM/LongBench/blob/main/pred.py)的`get_pred`中使用通过API的调用得到预测结果pred即可。

**Comment by jing-my** [comment]
请问是直接把prompt作为messages吗？samsum或者其它数据集是否需要什么额外的设置吗？

**Comment by bys0318** [comment]
是的，不需要额外的设置
