### ISSUE TITLE
能否发布画图代码

### ISSUE THREAD

**Issue by LiuShixing** [THUDM/LongBench#5]
1、很棒的工作，能否发布readme的图片绘制代码？
2、评测结果是取所有数据评测还是部分？（pred.py里面每个任务取10条数据）

**Comment by bys0318** [comment]
谢谢关注！对于您的问题：
1. 我们的雷达图是利用
```
from pyecharts.charts import Radar
```
这个工具包来绘制的。我们暂时没有发布绘图代码的计划，因为相关论文还在写作中。
2. 我们最终的评测结果都是在全集上测的，`pred.py`中现已将每个任务取10条数据更改为全集。
