### ISSUE TITLE
中文输出编码问题

### ISSUE THREAD

**Issue by wen2cheng** [THUDM/LongBench#7]
pred.py 在最后json输出的时候没有对中文进行编码处理
![image](https://github.com/THUDM/LongBench/assets/29756400/26adb584-dbb2-4047-ac8f-b7886d6e44a9)

**Comment by bys0318** [comment]
感谢指出！我们已经更新`pred.py`来支持中文编码。

**Comment by bojone** [comment]
`with open(f"pred/{dataset}.jsonl", "w") as f`要改为`with open(f"pred/{dataset}.jsonl", "w", errors="ignore") as f`，不然还会出现新的错误。

**Comment by wen2cheng** [comment]
设定一下输出的编码也可以，with open(f"pred/{dataset}.jsonl", "w",encoding='utf-8') as f

**Comment by bys0318** [comment]
感谢指正！我们已经将代码此处进行修改。
