### ISSUE TITLE
Why there is no need special token for chatglm3 when counting the tokens?

### ISSUE THREAD

**Issue by condy0919** [THUDM/LongBench#77]
https://github.com/THUDM/LongBench/blob/26505c81c149b0b6232e9e1ae4e9bac2477f0397/pred.py#L58-L59

**Comment by bys0318** [comment]
Hi, you can change it to `add_special_tokens=True`, but I guess a few special tokens do not matter much compared to a context window of 32k tokens.

**Comment by condy0919** [comment]
> I guess a few special tokens do not matter much compared to a context window of 32k tokens.

Agreed.
