### ISSUE TITLE
请问文章中图2 different truncation对应的评估代码在哪里呢？

### ISSUE THREAD

**Issue by HelloEveryonehh** [THUDM/LongBench#81]
作者您好，请问文章中图2 different truncation对应的评估代码在哪里？如果数据小于4k是否就不截断，还是直接不使用这个数据呢？

**Comment by bys0318** [comment]
你好，可以在[config/model2maxlen.json](https://github.com/THUDM/LongBench/blob/main/config/model2maxlen.json)中修改模型评测时候的输入长度上限。论文图2中，比如输入长度上限4k那么数据小于4k是否就不截断。

**Comment by HelloEveryonehh** [comment]
感谢您的回答！
