### ISSUE TITLE
LongBench v2 Evaluation regarding Qwen2.5

### ISSUE THREAD

**Issue by guanzhchen** [THUDM/LongBench#91]
Thanks for the solid benchmark. May I wonder if you use YaRN in the evaluation of Qwen2.5 series?

**Comment by bys0318** [comment]
We did not perform YaRN length extrapolation on the Qwen 2.5 series model, as it inherently supports a 128k context length. We truncated the sequences to 128k for testing.

**Comment by bys0318** [comment]
Hi, we tested Qwen2.5 series models without using YaRN. Thanks for pointing out this issue, we'll add Qwen2.5 results using YaRN during evaluation in the next version of our paper.

**Comment by bys0318** [comment]
We've updated the Qwen2.5 results on our leaderboard: https://longbench2.github.io to results evaluated using YaRN. An updated version of our paper will be uploaded to arXiv soon.

**Comment by guanzhchen** [comment]
Thanks for your reply and new results! I'm not sure if it's necessary to evaluate Qwen with YaRN, but glad to see both results.

**Comment by 1024er** [comment]
> We've updated the Qwen2.5 results on our leaderboard: https://longbench2.github.io to results evaluated using YaRN. An updated version of our paper will be uploaded to arXiv soon.

How should I modify the test command to support yarn? Thank you ~

**Comment by bys0318** [comment]
@1024er Hi, please see https://huggingface.co/Qwen/Qwen2.5-72B-Instruct#processing-long-texts, modify `config.json` and run vllm serving.
